/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class ConsultaSaldoFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultaSaldoFrame.class.getName());
    private Banco banco;
    /**
     * Creates new form ConsultaSaldoFrame
     */
    public ConsultaSaldoFrame(Banco banco) {
        initComponents();
        this.banco = banco;
        this.setLocationRelativeTo(null);
        this.setTitle("Consulta de Saldo");
        
        // Inicializar el label de saldo vacío o con guiones
        lblSaldo.setText("---");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCuenta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblTxtSaldo = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCuenta.setBackground(new java.awt.Color(204, 204, 204));
        txtCuenta.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        jPanel1.add(txtCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 160, -1));

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese Número de Cuenta:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 310, -1));

        lblTxtSaldo.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        lblTxtSaldo.setForeground(new java.awt.Color(255, 255, 255));
        lblTxtSaldo.setText("Saldo:");
        jPanel1.add(lblTxtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, 21));

        lblSaldo.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(255, 255, 255));
        lblSaldo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 109, 21));

        jButton1.setBackground(new java.awt.Color(239, 184, 16));
        jButton1.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Consultar");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String codCuenta = txtCuenta.getText().trim();
        
        if (codCuenta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un número de cuenta.");
            return;
        }

        Cuenta cuenta = banco.buscarCuenta(codCuenta);

        if (cuenta != null) {
            // Mostramos el saldo en el Label grande
            double saldo = cuenta.getSaldo(); 
            lblSaldo.setText("S/. " + String.format("%.2f", saldo));
        } else {
            JOptionPane.showMessageDialog(this, "Cuenta no encontrada.");
            lblSaldo.setText("---");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblTxtSaldo;
    private javax.swing.JTextField txtCuenta;
    // End of variables declaration//GEN-END:variables
}
