/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class ConsultaSaldoClienteFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultaSaldoClienteFrame.class.getName());
    private Banco banco;
    private Usuario usuario;
    /**
     * Creates new form ConsultaSaldoFrame
     */
    public ConsultaSaldoClienteFrame(Banco banco, Usuario usuario) {
        initComponents();
        this.banco = banco;
        this.usuario = usuario;
        this.setLocationRelativeTo(null);
        this.setTitle("Consulta de Saldo");

        // Inicializar el label de saldo
        lblNumSaldo.setText("---");

        // Llenar JComboBox con las cuentas del cliente
        comboBoxCuentas.removeAllItems();
        for (Titular t : banco.getListaTitular()) {
            if (t.getCliente().equals(((UsuarioCliente) usuario).getCliente())) {
                comboBoxCuentas.addItem(t.getCuenta().getCodigoCuenta());
            }
        }
        // Inicializar el label de saldo vacío o con guiones
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnConsultar = new javax.swing.JButton();
        lblTxtSaldo = new javax.swing.JLabel();
        comboBoxCuentas = new javax.swing.JComboBox<>();
        lblTxtCuentas = new javax.swing.JLabel();
        lblNumSaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        btnConsultar.setBackground(new java.awt.Color(239, 184, 16));
        btnConsultar.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        btnConsultar.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultar.setText("Consultar");
        btnConsultar.setBorderPainted(false);
        btnConsultar.addActionListener(this::btnConsultarActionPerformed);

        lblTxtSaldo.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        lblTxtSaldo.setForeground(new java.awt.Color(255, 255, 255));
        lblTxtSaldo.setText("Saldo:");

        comboBoxCuentas.setBackground(new java.awt.Color(204, 204, 204));
        comboBoxCuentas.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 12)); // NOI18N
        comboBoxCuentas.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxCuentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxCuentas.addActionListener(this::comboBoxCuentasActionPerformed);

        lblTxtCuentas.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        lblTxtCuentas.setForeground(new java.awt.Color(255, 255, 255));
        lblTxtCuentas.setText("Tus Cuentas:");

        lblNumSaldo.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        lblNumSaldo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTxtSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNumSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnConsultar)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(comboBoxCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblTxtCuentas)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(lblTxtCuentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBoxCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnConsultar)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTxtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        String codCuenta = (String) comboBoxCuentas.getSelectedItem();
        if (codCuenta == null) {
            JOptionPane.showMessageDialog(this, "No hay cuentas disponibles.");
            return;
        }

        // Buscamos la cuenta en el banco
        Cuenta cuenta = null;
        for (Titular t : banco.getListaTitular()) {
            if (t.getCuenta().getCodigoCuenta().equals(codCuenta)) {
                cuenta = t.getCuenta();
                break;
            }
        }

        if (cuenta != null) {
            lblNumSaldo.setText("S/. " + String.format("%.2f", cuenta.getSaldo()));
        } else {
            JOptionPane.showMessageDialog(this, "Cuenta no encontrada.");
            lblNumSaldo.setText("---");
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void comboBoxCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCuentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCuentasActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JComboBox<String> comboBoxCuentas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNumSaldo;
    private javax.swing.JLabel lblTxtCuentas;
    private javax.swing.JLabel lblTxtSaldo;
    // End of variables declaration//GEN-END:variables
}
