/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.*; 
/**
 *
 * @author Admin
 */
public class MenuClienteFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuClienteFrame.class.getName());

    /**
     * Creates new form MenuPrincipalFrame
     */
    private Banco banco;
    private GestorUsuarios gestor;
    private Usuario usuarioActual;

    public MenuClienteFrame(Banco banco, GestorUsuarios gestor, Usuario usuario) {
        initComponents();
        this.banco = banco;
        this.gestor = gestor;
        this.usuarioActual = usuario;
        this.setTitle("MEnu del Cliente");
        
        lblUsuario.setText(usuario.getNombreUsuario().toUpperCase());
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenuAdmin = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        lblNombreBanco1 = new javax.swing.JLabel();
        lblNombreBanco2 = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        btnSalir1 = new javax.swing.JButton();
        lblTxtRegistro1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanelMenuAdmin1 = new javax.swing.JPanel();
        logo1 = new javax.swing.JLabel();
        lblNombreBanco3 = new javax.swing.JLabel();
        lblNombreBanco4 = new javax.swing.JLabel();
        btnSalir2 = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSaldo = new javax.swing.JButton();
        btnDeposito = new javax.swing.JButton();
        btnRetiro = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnMovimientos = new javax.swing.JButton();
        lblTxtRegistro2 = new javax.swing.JLabel();

        jPanelMenuAdmin.setBackground(new java.awt.Color(239, 184, 16));
        jPanelMenuAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setForeground(new java.awt.Color(0, 0, 0));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoBanco.png"))); // NOI18N
        jPanelMenuAdmin.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        lblNombreBanco1.setFont(new java.awt.Font("OCR A Extended", 1, 22)); // NOI18N
        lblNombreBanco1.setForeground(new java.awt.Color(51, 51, 51));
        lblNombreBanco1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreBanco1.setText("USUARIO:");
        jPanelMenuAdmin.add(lblNombreBanco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 250, 30));

        lblNombreBanco2.setFont(new java.awt.Font("OCR A Extended", 1, 20)); // NOI18N
        lblNombreBanco2.setForeground(new java.awt.Color(51, 51, 51));
        lblNombreBanco2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreBanco2.setText("BIENVENIDO A iBank");
        jPanelMenuAdmin.add(lblNombreBanco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 250, 53));

        lblUsuario1.setFont(new java.awt.Font("OCR A Extended", 0, 22)); // NOI18N
        lblUsuario1.setForeground(new java.awt.Color(51, 51, 51));
        lblUsuario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario1.setText("mostrar el nombre del usuario");
        lblUsuario1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelMenuAdmin.add(lblUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 250, -1));

        btnSalir1.setBackground(new java.awt.Color(204, 204, 204));
        btnSalir1.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        btnSalir1.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir1.setText("Cerrar Sesión");
        btnSalir1.setBorderPainted(false);
        btnSalir1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir1.addActionListener(this::btnSalir1ActionPerformed);
        jPanelMenuAdmin.add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, 30));

        lblTxtRegistro1.setFont(new java.awt.Font("OCR A Extended", 1, 20)); // NOI18N
        lblTxtRegistro1.setForeground(new java.awt.Color(255, 255, 255));
        lblTxtRegistro1.setText("REGISTRO");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(630, 420));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenuAdmin1.setBackground(new java.awt.Color(239, 184, 16));
        jPanelMenuAdmin1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo1.setForeground(new java.awt.Color(0, 0, 0));
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logoBanco.png"))); // NOI18N
        jPanelMenuAdmin1.add(logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        lblNombreBanco3.setFont(new java.awt.Font("OCR A Extended", 1, 22)); // NOI18N
        lblNombreBanco3.setForeground(new java.awt.Color(51, 51, 51));
        lblNombreBanco3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreBanco3.setText("USUARIO:");
        jPanelMenuAdmin1.add(lblNombreBanco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 250, 30));

        lblNombreBanco4.setFont(new java.awt.Font("OCR A Extended", 1, 20)); // NOI18N
        lblNombreBanco4.setForeground(new java.awt.Color(51, 51, 51));
        lblNombreBanco4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreBanco4.setText("BIENVENIDO A iBank");
        jPanelMenuAdmin1.add(lblNombreBanco4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 250, 53));

        btnSalir2.setBackground(new java.awt.Color(204, 204, 204));
        btnSalir2.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        btnSalir2.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir2.setText("Cerrar Sesión");
        btnSalir2.setBorderPainted(false);
        btnSalir2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir2.addActionListener(this::btnSalir2ActionPerformed);
        jPanelMenuAdmin1.add(btnSalir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, 30));

        lblUsuario.setFont(new java.awt.Font("OCR A Extended", 0, 22)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("mostrar el nombre del usuario");
        lblUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelMenuAdmin1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 250, 30));

        jPanel1.add(jPanelMenuAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSaldo.setBackground(new java.awt.Color(204, 204, 204));
        btnSaldo.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        btnSaldo.setForeground(new java.awt.Color(0, 0, 0));
        btnSaldo.setText("Ver Saldo");
        btnSaldo.setBorderPainted(false);
        btnSaldo.addActionListener(this::btnSaldoActionPerformed);
        jPanel2.add(btnSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 120, -1));

        btnDeposito.setBackground(new java.awt.Color(204, 204, 204));
        btnDeposito.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        btnDeposito.setForeground(new java.awt.Color(0, 0, 0));
        btnDeposito.setText("Depósito");
        btnDeposito.setBorderPainted(false);
        btnDeposito.addActionListener(this::btnDepositoActionPerformed);
        jPanel2.add(btnDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 120, -1));

        btnRetiro.setBackground(new java.awt.Color(204, 204, 204));
        btnRetiro.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        btnRetiro.setForeground(new java.awt.Color(0, 0, 0));
        btnRetiro.setText("Retiro");
        btnRetiro.setBorderPainted(false);
        btnRetiro.addActionListener(this::btnRetiroActionPerformed);
        jPanel2.add(btnRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 120, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Tranferencia");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 120, -1));

        jSeparator1.setBackground(new java.awt.Color(239, 184, 16));
        jSeparator1.setForeground(new java.awt.Color(239, 184, 16));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, 380, 40));

        btnMovimientos.setBackground(new java.awt.Color(204, 204, 204));
        btnMovimientos.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        btnMovimientos.setForeground(new java.awt.Color(0, 0, 0));
        btnMovimientos.setText("Ver Movimientos");
        btnMovimientos.setBorderPainted(false);
        btnMovimientos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMovimientos.setFocusPainted(false);
        btnMovimientos.addActionListener(this::btnMovimientosActionPerformed);
        jPanel2.add(btnMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 140, -1));

        lblTxtRegistro2.setFont(new java.awt.Font("OCR A Extended", 1, 25)); // NOI18N
        lblTxtRegistro2.setForeground(new java.awt.Color(255, 255, 255));
        lblTxtRegistro2.setText("TRANSACCIONES");
        jPanel2.add(lblTxtRegistro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 380, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroActionPerformed
        // TODO add your handling code here:
        RetiroClienteFrame ret = new RetiroClienteFrame(banco, usuarioActual); 
        ret.setVisible(true);
    }//GEN-LAST:event_btnRetiroActionPerformed

    private void btnMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimientosActionPerformed
        // TODO add your handling code here:
        MovimientosClienteFrame ventana = new MovimientosClienteFrame(banco, usuarioActual);
    
        // Hacerla visible
        ventana.setVisible(true);
    }//GEN-LAST:event_btnMovimientosActionPerformed

    private void btnDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositoActionPerformed
        // TODO add your handling code here:
        DepositoClienteFrame dep = new DepositoClienteFrame(banco, usuarioActual);
        dep.setVisible(true);
        // No cerramos el menú (dispose) para que quede de fondo
    }//GEN-LAST:event_btnDepositoActionPerformed

    private void btnSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoActionPerformed
        // TODO add your handling code here:
        ConsultaSaldoClienteFrame consul= new ConsultaSaldoClienteFrame(banco, usuarioActual);
        consul.setVisible(true);

    }//GEN-LAST:event_btnSaldoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TransferenciaClienteFrame ventana = new TransferenciaClienteFrame(banco, usuarioActual);
        ventana.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        // TODO add your handling code here:
        new LoginFrame(banco, gestor).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
        // TODO add your handling code here:
        new LoginFrame(banco, gestor).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalir2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeposito;
    private javax.swing.JButton btnMovimientos;
    private javax.swing.JButton btnRetiro;
    private javax.swing.JButton btnSaldo;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JButton btnSalir2;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelMenuAdmin;
    private javax.swing.JPanel jPanelMenuAdmin1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblNombreBanco1;
    private javax.swing.JLabel lblNombreBanco2;
    private javax.swing.JLabel lblNombreBanco3;
    private javax.swing.JLabel lblNombreBanco4;
    private javax.swing.JLabel lblTxtRegistro1;
    private javax.swing.JLabel lblTxtRegistro2;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo1;
    // End of variables declaration//GEN-END:variables
}
