/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import modelo.*; 
import javax.swing.JOptionPane;
import java.util.ArrayList;
/**
 *
 * @author Admin
 */
public class TransferenciaClienteFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransferenciaClienteFrame.class.getName());
    private Banco banco;
    private UsuarioCliente usuarioCliente;
    // Lista auxiliar para guardar las cuentas reales y no solo el texto del combo
    private ArrayList<Cuenta> misCuentas;
    /**
     * Creates new form TransferenciaCliente
     */
    public TransferenciaClienteFrame(Banco banco, Usuario usuario) {
        initComponents();
        this.banco = banco;
        
        // Validamos que sea un cliente (por seguridad)
        if (usuario instanceof UsuarioCliente) {
            this.usuarioCliente = (UsuarioCliente) usuario;
        }
        
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setTitle("Transferencia - " + usuario.getNombreUsuario());
        
        cargarCuentasEnCombo();
    }
    private void cargarCuentasEnCombo() {
        cmbCuentasOrigen.removeAllItems(); // Limpiar
        
        // 1. Obtener el código del cliente logueado
        String codigoCliente = usuarioCliente.getCliente().getCodigoCliente();
        
        // 2. Buscar sus cuentas en el banco
        misCuentas = banco.buscarCuentasDeCliente(codigoCliente);
        
        // 3. Llenar el combo visualmente
        if (misCuentas.isEmpty()) {
            cmbCuentasOrigen.addItem("No tienes cuentas registradas");
            btnTransferir.setEnabled(false);
        } else {
            for (Cuenta c : misCuentas) {
                // Mostramos Código y Saldo para ayudar al usuario
                cmbCuentasOrigen.addItem(c.getCodigoCuenta() + " (Saldo: S/." + c.getSaldo() + ")");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbCuentasOrigen = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnTransferir = new javax.swing.JButton();
        txtMonto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbCuentasOrigen.setBackground(new java.awt.Color(204, 204, 204));
        cmbCuentasOrigen.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        cmbCuentasOrigen.setForeground(new java.awt.Color(0, 0, 0));
        cmbCuentasOrigen.addActionListener(this::cmbCuentasOrigenActionPerformed);
        getContentPane().add(cmbCuentasOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 176, -1));

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cuenta de Destino:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, -1));

        txtDestino.setBackground(new java.awt.Color(204, 204, 204));
        txtDestino.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        txtDestino.setForeground(new java.awt.Color(0, 0, 0));
        txtDestino.addActionListener(this::txtDestinoActionPerformed);
        getContentPane().add(txtDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 176, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTransferir.setBackground(new java.awt.Color(239, 184, 16));
        btnTransferir.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        btnTransferir.setForeground(new java.awt.Color(0, 0, 0));
        btnTransferir.setText("Transferir");
        btnTransferir.setBorderPainted(false);
        btnTransferir.addActionListener(this::btnTransferirActionPerformed);
        jPanel1.add(btnTransferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        txtMonto.setBackground(new java.awt.Color(204, 204, 204));
        txtMonto.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        txtMonto.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 176, -1));

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Monto:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 107, -1));

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cuenta de Origen:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Validar selección de cuenta origen
            int indiceSeleccionado = cmbCuentasOrigen.getSelectedIndex();
            if (indiceSeleccionado < 0 || misCuentas.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor selecciona una cuenta de origen.");
                return;
            }
            
            // Obtenemos el objeto Cuenta real usando la lista auxiliar y el índice
            Cuenta cuentaOrigen = misCuentas.get(indiceSeleccionado);
            
            // 2. Obtener y Validar datos de destino
            String ctaDestino = txtDestino.getText().trim();
            String montoStr = txtMonto.getText().trim();
            
            if (ctaDestino.isEmpty() || montoStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Complete todos los campos.");
                return;
            }
            
            // Validar que no se transfiera a sí mismo (misma cuenta)
            if (cuentaOrigen.getCodigoCuenta().equalsIgnoreCase(ctaDestino)) {
                JOptionPane.showMessageDialog(this, "No puedes transferir a la misma cuenta de origen.");
                return;
            }

            // 3. Validar Monto y Saldo
            double monto = Double.parseDouble(montoStr);
            if (monto <= 0) {
                JOptionPane.showMessageDialog(this, "El monto debe ser mayor a 0.");
                return;
            }
            
            // VERIFICACIÓN DE SALDO (Lo que pediste)
            if (cuentaOrigen.getSaldo() < monto) {
                JOptionPane.showMessageDialog(this, "Saldo insuficiente.\n" +
                        "Tu saldo actual es: S/." + cuentaOrigen.getSaldo());
                return;
            }

            // 4. Ejecutar Transferencia en el Banco
            String idTxn = "TXN" + System.currentTimeMillis();
            String codCliente = usuarioCliente.getCliente().getCodigoCliente();
            
            // Llamamos al método transferir del Banco
            // Nota: Pasamos 'null' en empleado porque lo hace el cliente directo
            Transaccion resultado = banco.transferir(codCliente, cuentaOrigen.getCodigoCuenta(), ctaDestino, monto, null, idTxn);
            
            if (resultado != null) {
                JOptionPane.showMessageDialog(this, "¡Transferencia Exitosa!\n" +
                        "Nuevo Saldo: S/." + cuentaOrigen.getSaldo());
                
                // Actualizar el combo para reflejar el nuevo saldo
                cargarCuentasEnCombo();
                // Seleccionar de nuevo la cuenta que se usó
                cmbCuentasOrigen.setSelectedIndex(indiceSeleccionado);
                
                // Limpiar campos
                txtDestino.setText("");
                txtMonto.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Error: Verifique que la cuenta destino exista.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un monto válido.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTransferirActionPerformed

    private void txtDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDestinoActionPerformed

    private void cmbCuentasOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCuentasOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCuentasOrigenActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransferir;
    private javax.swing.JComboBox<String> cmbCuentasOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
